### PR TITLE
Sync to latest DSPAL

### PR DESCRIPTION
**Pull request by mcharleb**

### CODE REVIEW

**Comment by LorenzMeier** [comment]
@mcharleb Are these fixing specific issues or is this just a housekeeping sync?

**Comment by julianoes** [comment]
@LorenzMeier I think we should probably just go back to ATLFlight instead of PX4
https://github.com/PX4/DriverFramework/blob/master/.gitmodules#L6

**Comment by mcharleb** [comment]
@LorenzMeier There were changes for APQ8096 (SLPI) support, support for correct DSP flags for 8074 and 8096, documentation fixes.

**Comment by mcharleb** [comment]
@julianoes I agree. I don't understand what PX4 could add to DSPAL without any changes to the image on the DSP, and I would rather get pull requests at ATLFlight for ant changes to DSPAL you think PX4 needs.

**Comment by LorenzMeier** [comment]
Can we close this and instead change the submodule URL in PX4/Firmware and delete this repo after ~1 month handover delay?

**Comment by mcharleb** [comment]
@LorenzMeier Yes, I'll close and I'll send a new PR to update the submodule to ATLFlight/dspal.

**Pull request closed without merging**
